### ISSUE TITLE
Error in README

### ISSUE THREAD

**Issue by afbjorklund** [sinwe/gradle-hazelcast-plugin#2]
Seems like the plugin id for `apply plugin` is wrong, there is no class name in the `build.gradle`:

https://github.com/sinwe/gradle-hazelcast-plugin/blob/master/build.gradle#L30

If you remove the class name, it works:

`apply plugin: "com.github.sinwe.gradle.caching.hazelcast"`

**Comment by afbjorklund** [comment]
```
* What went wrong:
A problem occurred evaluating settings 'test'.
> Plugin with id 'com.github.sinwe.gradle.caching.hazelcast.HazelcastPlugin' not found.

```

**Comment by sinwe** [comment]
@afbjorklund, Thank you for spotting that.
I didn't realize that the readme was wrong. I've correct it now.

**Comment by afbjorklund** [comment]
No problem! I was doing my own plugin (based on yours), and noticed that it wasn't working...

https://github.com/afbjorklund/gradle-memcached-plugin

At some point, it would be interest to compare rest/http* and memcached versus hazelcast ?

\* as in https://docs.gradle.com/build-cache-node/

**Comment by sinwe** [comment]
I've built an alternative HTTP based gradle cache server at [https://github.com/sinwe/http-gradle-cache-server](https://github.com/sinwe/http-gradle-cache-server). It's pretty simple for now, but I'm working on the version using microservices.

**Comment by afbjorklund** [comment]
Nice! Then we can use that instead, but I suppose any HTTP server would work ?
It will also be interesting to look closer at the "near cache" feature of hazelcast...

**Comment by sinwe** [comment]
There are 3 modes on my gradle http cache server: persistent, in-memory (default) and in-memory with replication. The one with in-memory with replication is based on hazelcast. So technically it is possible to have http based gradle cache server and hazelcast based cache to use the same hazelcast cluster. So whether to use http or map based, it will still be hitting the same cache object
